edx/edx-name-affirmation

CHANGELOG.rst, edx_name_affirmation/api.py, edx_name_affirmation/exceptions.py, edx_name_affirmation/tests/test_api.py
[MST-792](https://openedx.atlassian.net/browse/MST-792)
Adds `update_verification_attempt_id` to the VerifiedName API. This will update the user's most recent VerifiedName - this allows the user to create a VerifiedName, and finish ID verification later.
If the most recent VerifiedName already has a linked verification or proctored exam attempt, a new VerifiedName will be created instead.
It will raise an exception if the user does not have an existing VerifiedName.
=> [MST-792] Add update_verification_attempt_id

.coveragerc, CHANGELOG.rst, edx_name_affirmation/api.py, edx_name_affirmation/exceptions.py, edx_name_affirmation/tests/test_api.py
[MST-837](https://openedx.atlassian.net/browse/MST-837)
Provide a way to update the `is_verified` status of a VerifiedName, intended for use when the linked ID verification or proctored exam attempt is approved.
=> [MST-837] Add update_is_verified_status

edx_name_affirmation/serializers.py, edx_name_affirmation/tests/test_views.py, edx_name_affirmation/views.py
Add post endpoint to create new verified name. Endpoint will return:
* 403 if non-staff user is attempting to create a verified name for another user
* 400 if both `proctored_exam_attempt_id` and `verification_attempt_id` are included in request
* 400 if data is invalid
=> feat: add post endpoint for VerifiedName

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/apps.py
[MST-883](MST-883)
Adds plugin support as described in [edx-django-utils](https://github.com/edx/edx-django-utils/tree/master/edx_django_utils/plugins).
=> [MST-883] Add plugin support

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/tests/test_views.py, edx_name_affirmation/views.py
Adds an attribute to the GET response of the VerifiedNameView view, indicating whether the verified name feature is enabled.
**JIRA:**
[MST-800](https://openedx.atlassian.net/browse/MST-800)
=> feat: Add verified_name_enabled to VerifiedNameView GET response

.annotation_safe_list.yml, CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/admin.py, edx_name_affirmation/api.py, edx_name_affirmation/serializers.py, edx_name_affirmation/tests/test_admin.py, edx_name_affirmation/tests/test_api.py, edx_name_affirmation/tests/test_views.py, edx_name_affirmation/urls.py, edx_name_affirmation/views.py, test_settings.py
Add `use_verified_name_for_certs` field to the VerifiedNameView response, and create a new endpoint to update the user's verified name config.
Also added admin pages for VerifiedName and VerifiedNameConfig as they had not been configured yet.
**JIRA:**
[MST-893](https://openedx.atlassian.net/browse/MST-893)
=> [MST-893] Update REST API to include config model

CHANGELOG.rst, MANIFEST.in, edx_name_affirmation/__init__.py
The PyPI package was missing all files from the child directories in edx_name_affirmation (migrations, tests, etc). This should fix that.
**JIRA:**
[MST-949](https://openedx.atlassian.net/browse/MST-949)
=> [MST-949] Add missing graft command to MANIFEST.in

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/api.py, edx_name_affirmation/tests/test_api.py, edx_name_affirmation/tests/test_views.py, edx_name_affirmation/urls.py, edx_name_affirmation/views.py
Add an API and endpoint to retrieve a list of all the user's verified names in order of most recently created.
**JIRA:**
[MST-945](https://openedx.atlassian.net/browse/MST-945)
=> [MST-945] Add verified name history API

CHANGELOG.rst, edx_name_affirmation/__init__.py, test_settings.py
You can't run for example manage.py migrate right now without disabling admin in settings.
This seems to be the minimal set of changes required to get that to run again.
=> fix: put enough admin support into the settings file to actually run

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/models.py
Takes a few releases to safely get rid of the field.
MST-969
=> feat: continue removing verified name is_verified

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/admin.py, edx_name_affirmation/tests/test_admin.py
This check doesn't happen until you actually run django i.e. manage.py makemigrations so I missed it in earlier PRs. We probably want an automated check that runs manage.py check.
Also I'm not thrilled with the test, it just compares lists of strings in the setup and test files. I think we could drop that entire test file and lose only coverage numbers - django admin is tested by django, we're just setting it up.
MST-969
=> fix: update admin to use status instead of is_verified

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/apps.py, edx_name_affirmation/handlers.py, edx_name_affirmation/statuses.py, edx_name_affirmation/tests/test_handlers.py, edx_name_affirmation/urls.py, requirements/base.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.in, requirements/test.txt
This PR should not be merged/deployed until https://github.com/edx/edx-proctoring/pull/938 and https://github.com/edx/edx-platform/pull/28511 have been merged/deployed. 
This PR defines two signal receivers, one for IDV updates and the other for proctoring updates. These receivers determine what changes to an IDV or proctoring attempt should trigger any changes for a VerifiedName. We have determined these triggers in this chart: https://lucid.app/lucidchart/8452b1f5-fd3d-4aeb-a6ef-66c9f01b1293/edit?shared=true&page=0_0#
The signal receivers will only be connected if name affirmation is enabled.
**JIRA:**
[MST-972](https://openedx.atlassian.net/browse/MST-972)
=> feat: add signal receivers for edx_name_affirmation

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/apps.py, edx_name_affirmation/handlers.py, edx_name_affirmation/signals.py, edx_name_affirmation/tests/test_handlers.py
Add a post save handler for VerifiedName that emits a signal with `user` and `profile_name` when its status changes to "approved".
**JIRA:**
[MST-803](https://openedx.atlassian.net/browse/MST-803)
=> [MST-803] Add signal handler for verified name approved

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/api.py, edx_name_affirmation/tests/test_api.py
Exposes the toggle out via the api, everything in api is exposed via the service
MST-1020
=> feat: add state of feature toggle to API for general use

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/handlers.py
Update `full_name` -> `photo_id_name` and `profile_name` -> `full_name`, in order to be clearer that:
- `photo_id_name` is what's sent to the IDV provider (and therefore used as the verified name)
- `full_name` may not necessarily be the user's current profile name, but instead a pending name change
**JIRA:**
[MST-1025](https://openedx.atlassian.net/browse/MST-1025)
=> [MST-1025] Update IDV signal handler field names

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/tests/test_views.py, edx_name_affirmation/urls.py, edx_name_affirmation/views.py
We provide the enabled flag with the verified name object if it exists or the history. For this particular use we don't need the full history but the verified name object may 404, so we need a separate flag endpoint.
Also connects the other use of this flag in the views to the API function rather than the toggle function for consistency.
[MST-1026](https://openedx.atlassian.net/browse/MST-1026)
=> feat: endpoint exposing the API's verified name enabled flag

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/name_change_validator.py, edx_name_affirmation/tests/test_name_change_validator.py
Add class for name change validation. 
Name changes are considered valid if either:
* a user has no certificates,
* the changes only contain a one character difference 
* user has not changed their name more than 2 times previously
Changes are not valid if:
* two or more characters are changed
* a user is attempting to change their name for the third time
* multiple spaces occur in a row
**JIRA:**
[MST-970](https://openedx.atlassian.net/browse/MST-970)
=> feat: Add name change validator

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/tasks.py, edx_name_affirmation/tests/test_tasks.py
Set the IDV and proctoring celery tasks to retry up to 3 times with any exception. We can refine this later if we notice any patterns.
**JIRA:**
[MST-1071](https://openedx.atlassian.net/browse/MST-1071)
=> [MST-1071] Add retry logic to celery tasks

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/handlers.py, edx_name_affirmation/tasks.py, edx_name_affirmation/tests/test_handlers.py
If we receive a non-relevant status for either an IDV or proctoring update, we should not trigger a celery task. This change means that if a non-relevant status is included in the first event name affirmation receives, no verified name will be created. This should not be an issue, as other signals that include a relevant status will eventually be captured.  
I've also added two new tasks that we can cut over to after this PR is merged. 
**JIRA:**
[MST-1145](https://openedx.atlassian.net/browse/MST-1145)
=> fix: reduce number of celery tasks for idv and proctoring updates

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/handlers.py, edx_name_affirmation/tests/test_handlers.py, edx_name_affirmation/tests/test_tasks.py
Now that the new name affirmation tasks have been registered, we should cut over to them. The old tasks will still remain in place to allow any remaining celery tasks in the queue to complete successfully. After that, we can remove the old tasks completely.
Won't merge until https://github.com/edx/edx-platform/pull/29333 is deployed.
**JIRA:**
[MST-1145](https://openedx.atlassian.net/browse/MST-1145)
=> feat: cut over to new name affirmation tasks

requirements/base.txt, requirements/celery50.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, tox.ini
1. Requirements had been failing due to a minor version celery release requiring a major version bump in click.
2. The pii job is broken as of the Django 4 release. Wait but there's a constraint file and we aren't even on 3.0 yet?! Yes, but it turns out there's a bit of a foot gun in here. Any constraints on the django version are scrubbed on test.txt with the expectation the default tox testenv would set it. Creating different environments for quality, pii_check, etc that use test.txt alone will just install the most recent version of django. 🤦  
There's probably a better tox/make refactor to avoid this trap, but this unblocks things at least for now.
@edx/masters-devs-cosmonauts
=> Fix requirements update

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/api.py, edx_name_affirmation/tests/test_api.py
Add the ability to filter out a list of statuses when calling `get_verified_name`.
**JIRA:**
[MST-1275](https://openedx.atlassian.net/browse/MST-1275)
=> [MST-1275] Add `statuses_to_exclude` arg to `get_verified_name`

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/statuses.py, edx_name_affirmation/tests/test_handlers.py
Students who take a proctored exam and receive an `error` status are blocked from making changes to their name. This is because name affirmation only triggers verified name updates based on certain proctored exam statuses (`error` was previously not one of the statuses that would trigger a verified name update). To allow learners the ability to change their name, we should handle `error` status updates from proctored exams.
**JIRA:**
[MST-1375](https://openedx.atlassian.net/browse/MST-1375)
=> fix: allow error status updates to trigger verified name updates

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/api.py, edx_name_affirmation/serializers.py, edx_name_affirmation/tests/test_views.py, edx_name_affirmation/urls.py, edx_name_affirmation/views.py
Add REST API functionality to update verified name status, and to delete verified names. Both require staff access.
**JIRA:**
[MST-1361](https://openedx.atlassian.net/browse/MST-1361)
=> [MST-1361] Add patch and delete to VerifiedNameView

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/apps.py, edx_name_affirmation/handlers.py, edx_name_affirmation/tasks.py, edx_name_affirmation/tests/test_handlers.py, edx_name_affirmation/tests/test_tasks.py
If a proctored exam attempt or an IDV attempt are deleted, we should capture that `post_delete` signal to delete any VerifiedNames associated with the deleted attempt. 
Any `post_delete` signal will trigger a celery task, although I don't anticipate this causing too much noise. We've had ~1300 deleted proctoring attempts since 1/01/22 which averages to about 20 deletes a day.
**JIRA:**
[MST-1394](https://openedx.atlassian.net/browse/MST-1394)
=> feat: if a proctored exam or IDV attempt is deleted, we should delete the VerifiedName

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/tests/test_models.py, edx_name_affirmation/views.py, requirements/base.in, requirements/base.txt, requirements/celery50.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt
Leverage edx-api-doc-tools to provide better swagger documentation for the RESTFul API endpoints
**JIRA:**
[MST-1457](https://openedx.atlassian.net/browse/MST-1457)
See screenshot:
=> fix: Add detailed api docs to the RESTFul APIs

requirements/base.txt, requirements/celery50.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt
pluggy version conflicts generated from other requirements seem to have resolved to 1.0.0 so we can remove that constraint
=> rm pluggy constraint

CHANGELOG.rst, edx_name_affirmation/__init__.py, edx_name_affirmation/tasks.py, edx_name_affirmation/tests/test_handlers.py
Currently if a user tries to submit an IDV attempt with the same name as a previous IDV attempt that was reviewed, no verified name record will be created for them. 
Splunk logs will show that in this case, it looks like a verified name _is_ actually created for the learner, even though no record is actually created.
**JIRA:**
[MST-1514](https://2u-internal.atlassian.net/browse/MST-1514)
=> fix: allow verified name to be created if user is trying to verify with the same name

openedx.yaml
Update the release metadata ahead of the Olive release.
=> build: no need for Open edX branching, because this repo is a dependency.

.github/workflows/publish-pypi.yml, .github/workflows/upgrade-python-requirements.yml, docs/conf.py
The previous upgrade of the Python version from 3.8 to 3.11 didn't upgrade the version used to install requirements and push to PyPI. This commits upgrades the version of Python used in those actions to 3.11.
**JIRA:**
None.
=> build: update version of Python used from 3.8 to 3.11

edx_name_affirmation/models.py, edx_name_affirmation/serializers.py, edx_name_affirmation/tests/test_models.py, edx_name_affirmation/tests/test_views.py
The purpose of this update is to decouple the [VerifiedName](https://github.com/openedx/frontend-app-support-tools/blob/e96d171f8241026652abdfcd319a70f2d33d31aa/src/users/VerifiedName.jsx#L15) component in the [Support Tools MFE](https://github.com/openedx/frontend-app-support-tools) from the [verify_student](https://github.com/openedx/edx-platform/tree/master/lms/djangoapps/verify_student) application. The [VerifiedName](https://github.com/openedx/frontend-app-support-tools/blob/e96d171f8241026652abdfcd319a70f2d33d31aa/src/users/VerifiedName.jsx#L15) component is used to display a table of verified name information in the [Support Tools](https://github.com/openedx/frontend-app-support-tools). A screenshot is attached.
The solution might not be the most optimal, since it …
=> Add IDV Status to VerifiedName

Makefile
This commit removes a line in the upgrade Make target that attempts to delete a file that doesn't exist. The lines that generated the file that is being deleted were deleted in a previous commit.
**JIRA:**
None.
=> Fix build Make target.

edx_name_affirmation/__init__.py, edx_name_affirmation/apps.py
Updating the signal path for the `idv_attempt_handler` to match the new signals directory structure in `edx-platform`. This is required in order to get https://github.com/openedx/edx-platform/pull/35468 to work.
Describe in a couple of sentences how this pull request modifies the repository.
**JIRA:**
[XXX-XXXX](https://openedx.atlassian.net/browse/XXX-XXXX)
=> chore: update idv signal url

edx_name_affirmation/__init__.py, edx_name_affirmation/models.py, edx_name_affirmation/signals.py, edx_name_affirmation/tests/test_signals.py
The purpose of this ticket is to hook the [VerifiedName](https://github.com/edx/edx-name-affirmation/blob/main/edx_name_affirmation/models.py#L17) model of the [edx-name-affirmation](https://github.com/edx/edx-name-affirmation) application into the LMS retirement pipeline.
**JIRA:**
[COSMO-465](https://2u-internal.atlassian.net/browse/COSMO-465)
=> feat: create lms retirement listener for verified name

CHANGELOG.rst, edx_name_affirmation/admin.py, edx_name_affirmation/api.py, edx_name_affirmation/models.py, edx_name_affirmation/serializers.py, edx_name_affirmation/tests/test_api.py, edx_name_affirmation/tests/test_models.py, edx_name_affirmation/tests/test_views.py, edx_name_affirmation/views.py
This PR integrates the newly added `platform_verification_attempt_id` field into the name affirmation code.
**JIRA:**
[COSMO-495](https://2u-internal.atlassian.net/browse/COSMO-495)
=> feat: integrate platform verification attempt

edx_name_affirmation/models.py
I noticed this typo while testing the support tools frontend work for https://2u-internal.atlassian.net/browse/COSMO-496. 
=> fix: fix typo in import path

.github/workflows/upgrade-python-requirements.yml
The python requirements upgrade workflow is currently failing (see https://github.com/edx/edx-name-affirmation/actions/runs/12272970013/job/34382900297). Attempting to remove the specified python version, as is done in a few other repos, to see if this helps.
=> fix: attempting to debug requirements workflow

requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.txt
Click version 8.1.7 was causing issues with compiling requirements. Manually upgrading to 8.1.8, and verified that the `make upgrade` and `make requirements` commands still work.
=> fix: manually upgrade requirements
